Add controllers
Fenris06/java-shareit pull request #1
Opened 2023-04-19 20:24 UTC by Fenris06

2023-04-19 20:41 UTC, Fenris06 commented
Привет. Работу сделал. Жду замечаний)).

2023-04-20 19:18 UTC, ohelly requested changes
Привет! Отличная работа, прекрасный код! У меня нет замечаний, есть только пара рекомендаций. Их исправлять необязательно, можешь просто отправить на проверку текущий вариант работы и я ее приму. Также еще советую попробовать написать мапперы с помощью мапстракта, прикольная вещь.
https://www.baeldung.com/mapstruct

2023-04-20 19:18 UTC, ohelly commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +   private String status;
Рекомендация: Для поля status можно создать отдельный enum.

2023-04-20 19:18 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/service/ItemMapper.java
> +package ru.practicum.shareit.item.service;
Рекомендация: Будет лучше если для маппера создать отдельный пакет, так как он не относится к сервисной логике.
Аналогично для всех остальных.

2023-04-21 19:20 UTC, Fenris06 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +   private String status;
Поправил

2023-04-21 19:21 UTC, Fenris06 commented on src/main/java/ru/practicum/shareit/item/service/ItemMapper.java
> +package ru.practicum.shareit.item.service;
Поправил.

2023-04-21 19:28 UTC, Fenris06 commented
Еще раз привет. Спасибо огромное за библиотеку. Переделал маперы с ее использованием.

2023-04-22 16:44 UTC, ohelly approved these changes
Привет! Все выполнено отлично! Работу принимаю, можно двигаться дальше. Удачи в дальнейшем обучении!

2023-04-22 16:44 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapstructMapper.java
> +@Mapper
Чтобы маппер можно было инжектить как другие спринг бины(через конструкторы или через ``@Autowired``) можно добавить следующее: ``@Mapper(componentModel="spring")``

2023-04-22 17:04 UTC, Fenris06 commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapstructMapper.java
> +@Mapper
Спасибо. Обязательно воспользуюсь.

2023-04-22 17:04 UTC, merged