Add bookings
Fenris06/java-shareit pull request #2
Opened 2023-05-15 16:57 UTC by Fenris06

Привет! В этот раз столкнулся с проблемой циклической зависимости в ItemService когда появилась необходимость заинжектить в него BookingService. Переделал на хождения в разные репозитории. Не очень понял как в таком случаи быть, если нужно в смежные сервисы инжектить. Или же все таки правильно ходить из сервисов по репозиториям? В работе которая в теории сервисы ходят по репозиториям. Еще интересно узнать твое мнение на тему лишний раз сходить в базу или  выгрузить из базы за один заход и потом в сервисе обрабатывать? Я решил находить last и next букинг за один заход в базу. Но возможно для каждого букинга было бы проще выгружать отдельно нужные данные и уже работать с ними. Как в общем лучше? Или тоже от ситуации зависит? А еще пока отказался от vapstructur в связи с тем что более сложные DTO и пока не получилось разобраться как их делать. Постираюсь к следующему разу переписать их.

2023-05-15 19:20 UTC, Fenris06 commented
Забыл аннотацию транзакций добавить. Добавлю после твоих замечаний.

2023-05-16 18:08 UTC, ohelly requested changes
Привет! В целом отличная работа, все работает корректно. Есть несколько рекомендаций, на которые стоит обратить внимание. Их выполнение на твое усмотрение.

2023-05-16 18:08 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      private Long id;
Рекомендация: Будет лучше писать аннотацию ``@Column`` для всех полей, даже если их название идентично названию колонок в БД. Это прибавляет читаемость коду + оберегает от возможных ошибок, например если вдруг изменится название поля в классе через функции рефактор в IDEA.

2023-05-16 18:08 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/storage/ItemRepository.java
> +            "where upper(i.name) like upper(concat('%', ?1, '%')) " +
Рекомендация: Параметры также можно указывать через нейминг, вместо цифр:
![image](https://github.com/Fenris06/java-shareit/assets/51891976/874fb0df-8b5f-43bb-93b5-e70079699fdf)
Данная рекомендация больше нацелена на то, чтобы показать альтернативный вариант, использовать можно любой, существенной разницы нет

2023-05-16 18:08 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceJpa.java
> +    private final UserRepository userRepository;
Рекомендация: Будет лучше, если данный сервис будет обращаться напрямую только к "своему" репозиторию(ItemRepository), а к остальным через их сервисы. Такой подход более правильный, так как в сервисах может находится дополнительная логика, влияющая на выдачу результата.

2023-05-16 18:08 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceJpa.java
> +    private List<Booking> findFirstBookings(List<Booking> bookings, LocalDateTime dateTime) {
Рекомендация: Данный метод и метод ниже можно заменить на запрос в БД. Например взять текущую дату и найти все букинги у которых дата до текущей при этом отсортировав по убыванию и взять первый. Для метода аналогично, но уже в обратную сторону.

2023-05-16 18:20 UTC, ohelly commented
> Привет! В этот раз столкнулся с проблемой циклической зависимости в ItemService когда появилась необходимость заинжектить в него BookingService. Переделал на хождения в разные репозитории. Не очень понял как в таком случаи быть, если нужно в смежные сервисы инжектить. Или же все таки правильно ходить из сервисов по репозиториям? В работе которая в теории сервисы ходят по репозиториям. Еще интересно узнать твое мнение на тему лишний раз сходить в базу или выгрузить из базы за один заход и потом в сервисе обрабатывать? Я решил находить last и next букинг за один заход в базу. Но возможно для каждого букинга было бы проще выгружать отдельно нужные данные и уже работать с ними. Как в общем лучше? Или тоже от ситуации зависит? А еще пока отказался от vapstructur в связи с тем что более сложные DTO и пока не получилось разобраться как их делать. Постираюсь к следующему разу переписать их.

Сначала оставил комменты и только потом увидел это сообщение :D

Ну если циклическая зависимость, то можно и в репы ходить, это не критично. Вообще есть варианты решения этой проблемы всякими костылями, но это такой себе вариант. Либо можно сделать чтобы один ходил в репозиторий, а другой в сервис, но тут уже на твое усмотрение.

На счет лишнего запроса в БД - в твоем случае найти last и next можно в целом вообще за два запроса(по одному на каждый), а так конечно да - зависит от ситуации, но с одним замечанием - если выгружать все данные(findAll к примеру), а затем в сервисе их как то фильтровать - плохой вариант, потому что записей в БД может быть очень много(миллионы и десятки миллионов) и если их всех выгрузить в память приложения, то оно скорее всего упадет) БД для этого и создано, чтобы с помощью нее как то работать с большим объемом данных не выгружая их в память приложения. Итого - когда достаем один итем - достаточно двух запросов для получения last и next, при множественной выборке итемов - количество итемов * 2 = кол-во запросов необходимых для получения last и next.

2023-05-17 10:10 UTC, Fenris06 commented
Привет! Спасибо за ревью. Код решил пока не трогать. Есть пару идей улучшений, но хочется начать уже следующее задание и решил отложить на будущее)). Добавил название колонок в модели и аннотацию @Transaction в сервисы.
Касаемо моего случая с цикличной зависимостью. У меня была идея создать отдельный сервис BookingItem service, в который я заинжектил бы BookingService и уже через него ходил бы в нужные методы Booking service для Item service.
Или может лучше в  BookingItem service заинжектить было бы BookingRepository и создать нужные методы в нем? В общем я много думал над тем ка в моем случаи выйти из сложившегося положения и но так и не придумал как это сделать(кроме перехода на запросы в репозитории).

2023-05-17 18:18 UTC, ohelly commented
> Привет! Спасибо за ревью. Код решил пока не трогать. Есть пару идей улучшений, но хочется начать уже следующее задание и решил отложить на будущее)). Добавил название колонок в модели и аннотацию @transaction в сервисы. Касаемо моего случая с цикличной зависимостью. У меня была идея создать отдельный сервис BookingItem service, в который я заинжектил бы BookingService и уже через него ходил бы в нужные методы Booking service для Item service. Или может лучше в BookingItem service заинжектить было бы BookingRepository и создать нужные методы в нем? В общем я много думал над тем как в моем случаи выйти из сложившегося положения но так и не придумал как это сделать(кроме перехода на запросы в репозитории).

Привет! Отдельный сервис создавать точно не стоит, получится сервис ради сервиса и их может при таком подходе расплодится, что будет очень плохо) Ходить в репу напрямую - нормально, особенно в твоем случае, так что не нужно из-за этого переживать) Другого варианта я пока не придумал

2023-05-17 18:22 UTC, ohelly approved these changes
Привет! Все супер, отличная работа. Задание принимаю, можно двигаться дальше!

2023-05-17 18:22 UTC, ohelly commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    @Transactional
Рекомендация: Аннотацию ``@Transactional`` в интерфейсе можно не писать, в классе реализации вполне достаточно. Разработчика спринга также не рекомендуют их ставить над интерфейсами, потому что может привести к неожидаемому поведению

2023-05-17 18:22 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
>  public interface ItemService {
Рекомендация: Аналогично аннотацию можно удалить из интерфейса.

2023-05-17 19:44 UTC, merged