Add item requests
Fenris06/java-shareit pull request #3
Opened 2023-05-21 21:42 UTC by Fenris06

2023-05-24 23:58 UTC, Fenris06 commented
Привет. Опять тесты помучали меня))). Довольно много времени на них потратил. Выяснил, что с Hibernate не рекомендуются переопределять Equals и HashCod и убрал с классов аннотации.  Ну а дальше начались проблемы с моками)). В итоги методы в которые приходят объекты мокал через any() и название класса. Какие еще есть варианты в таком случаи тестировать с помощью моков? Ну и с интеграционными тоже помучался. Долго не мог сообразить что базу нужно чистить в правильной последовательности))). Кстати есть еще какие-нибудь варианты чистить базу кроме вызовов методов репозитория? И я правильно понимаю что не получится сделать так, чтобы спринг для каждого класса тестов заново поднимал базу?

2023-05-25 19:39 UTC, ohelly requested changes
Привет! Отличная работа, все раюотает корректно, замечаний нет. Есть одна рекомендация, ее выполнение на твое усмотрение.

2023-05-25 19:39 UTC, ohelly commented on src/main/java/ru/practicum/shareit/request/service/impl/ItemRequestServiceImpl.java
> +    private List<ItemRequestGetAnswerDTO> setItemsToRequests(List<ItemRequest> itemRequests, List<Item> items) {
Рекомендация: Данный метод можно переделать с использованием HashMap, аналогично тому как было сделано в 11 работе. Это повысит проихводительность.

2023-05-26 10:25 UTC, Fenris06 commented on src/main/java/ru/practicum/shareit/request/service/impl/ItemRequestServiceImpl.java
> +    private List<ItemRequestGetAnswerDTO> setItemsToRequests(List<ItemRequest> itemRequests, List<Item> items) {
Спасибо за ревью. Что то не получилось у меня через стрим из списка itemRequests  создать map по ключу и объекту. В общем пока оставлю без изменений, но  идею понял.

2023-05-27 10:25 UTC, ohelly commented
> Привет. Опять тесты помучали меня))). Довольно много времени на них потратил. Выяснил, что с Hibernate не рекомендуются переопределять Equals и HashCod и убрал с классов аннотации. Ну а дальше начались проблемы с моками)). В итоги методы в которые приходят объекты мокал через any() и название класса. Какие еще есть варианты в таком случаи тестировать с помощью моков? Ну и с интеграционными тоже помучался. Долго не мог сообразить что базу нужно чистить в правильной последовательности))). Кстати есть еще какие-нибудь варианты чистить базу кроме вызовов методов репозитория? И я правильно понимаю что не получится сделать так, чтобы спринг для каждого класса тестов заново поднимал базу?

https://stackoverflow.com/questions/34617152/how-to-re-create-database-before-each-test-in-spring
Для очистки БД можно глянуть в эту сторону.

По поводу моков объектов - да в принципе твой вариант хороший, этого будет вполне достаточно.

2023-05-27 10:25 UTC, ohelly approved these changes
Привет! Все супер, работу принимаю. Удачи в дальнейшем обучении!

2023-05-29 09:04 UTC, merged