Add docker
Fenris06/java-shareit pull request #4
Opened 2023-06-02 13:51 UTC by Fenris06

2023-06-02 16:57 UTC, Fenris06 commented
Привет. Что то на радостях, что проект все проверки прошел  забыл перенести тесты из server в gatvay которые упали. Закоммитил их и забыл про них))). И по поводу общего пома. Я там зависимости не почистил. Я так понимаю что их от туда нужно убрать?

2023-06-03 12:02 UTC, AnastasiyaFomkina requested changes

2023-06-03 12:02 UTC, afomkina commented on gateway/src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public ResponseEntity<Object> getBookings(@RequestHeader("X-Sharer-User-Id") long userId,
Нужно вынести повторяющийся хэдер в отдельный класс и сделать его публичной константой, чтобы избежать дублирований в других классах. Чтобы быстро поправить все значения, можно воспользоваться горячими клавишами в IDEA: [Ctrl+Shift+R](https://www.jetbrains.com/help/idea/finding-and-replacing-text-in-project.html?keymap=primary_windows#replace_search_string_in_project)

2023-06-03 12:02 UTC, afomkina commented on gateway/src/main/java/ru/practicum/shareit/user/client/UserClient.java
> +
Лишние отступы

2023-06-03 12:02 UTC, afomkina commented on gateway/src/main/resources/application.properties
> +#logging.level.httpclient.wire=DEBUG
Нужно удалить неиспользуемые проперти

2023-06-03 12:02 UTC, afomkina commented on gateway/src/main/java/ru/practicum/shareit/comment/dto/CommentDTO.java
>      String text;
Не хватает модификатора доступа

2023-06-03 12:02 UTC, afomkina commented on gateway/pom.xml
> +            <artifactId>spring-boot-starter-test</artifactId>
Эта зависимость лишняя, так как в данном модуле нет тестов

2023-06-03 12:02 UTC, afomkina commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
Валидация должна быть только в `pom` модуля `gateway`

2023-06-03 12:02 UTC, afomkina commented on pom.xml
>  		<groupId>org.springframework.boot</groupId>
В корневом `pom` файле нужно оставить только повторяющиеся для обоих модулей зависимости, а все лишнее - нужно удалить, так как большинство из сейчас подключенный здесь зависимостей совершенно не нужны в модуле `gateway`
В принципе здесь вообще можно удалить блок `dependencies` и `profiles`. Зависимости для каждого модуля нужно будет обозначить свои, а прифилирование переехало в `server`

2023-06-03 12:02 UTC, afomkina commented on pom.xml
> +		<module>server</module>
Поправь, пожалуйста, разметку файла, это легко сделать с помощью сочетания клавиш [Ctrl+Alt+L](https://www.jetbrains.com/idea/guide/tips/reformat-file/) в Idea.

2023-06-03 12:02 UTC, afomkina commented on server/src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +//    @SneakyThrows
Нужно удалить тесты с валидацией, а не комментировать код.
Если будет время - идеально будет их перенести в модуль `gateway`

2023-06-03 12:02 UTC, afomkina commented on server/src/main/java/ru/practicum/shareit/user/dto/UserDTO.java
> +import lombok.*;
_Саморазвитие_
В коммерческой разработке не принято использовать `wildcard` в импортах.
Вот отличная [статья](https://struchkov.dev/blog/using-wildcard-imports-in-java/) почему и как настроить идею, чтобы избавиться от `*`
Кстати, в IDEA есть отличное сочетание клавиш `Ctrl + Alt + O` - при нажатии сочетания в нужном классе автоматически оптимизируются импорты и удаляются ненужные

2023-06-03 16:58 UTC, Fenris06 commented on gateway/src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public ResponseEntity<Object> getBookings(@RequestHeader("X-Sharer-User-Id") long userId,
Создал  по классу в Servere и Gatway и заменил на константу во всех контроллерах. Правда почему то не получилось через Ctrl-Shift-R. Идея не холе находить новый класс со статической переменной.

2023-06-03 16:58 UTC, Fenris06 commented on gateway/src/main/java/ru/practicum/shareit/user/client/UserClient.java
> +
Убрал

2023-06-03 16:58 UTC, Fenris06 commented on gateway/src/main/resources/application.properties
> +#logging.level.httpclient.wire=DEBUG
Удалил

2023-06-03 16:58 UTC, Fenris06 commented on gateway/src/main/java/ru/practicum/shareit/comment/dto/CommentDTO.java
>      String text;
добавил privat

2023-06-03 16:59 UTC, Fenris06 commented on gateway/pom.xml
> +            <artifactId>spring-boot-starter-test</artifactId>
Убрал

2023-06-03 16:59 UTC, Fenris06 commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
Убрал

2023-06-03 17:00 UTC, Fenris06 commented on pom.xml
>  		<groupId>org.springframework.boot</groupId>
Помы почистил.

2023-06-03 17:00 UTC, Fenris06 commented on pom.xml
> +		<module>server</module>
Поправил

2023-06-03 17:00 UTC, Fenris06 commented on server/src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +//    @SneakyThrows
По времени не успеваю поменять. Решил просто удалить.

2023-06-03 17:09 UTC, Fenris06 commented on server/src/main/java/ru/practicum/shareit/user/dto/UserDTO.java
> +import lombok.*;
У разных ревьюеров на это счет разный взгляд. И я так понял что это больше зависит от того как в команде разработки принято. Но статья очень полезная. Спасибо за нее.

2023-06-04 13:04 UTC, AnastasiyaFomkina commented
> Привет. Что то на радостях, что проект все проверки прошел забыл перенести тесты из server в gatvay которые упали. Закоммитил их и забыл про них))). И по поводу общего пома. Я там зависимости не почистил. Я так понимаю что их от туда нужно убрать?

Можно полностью удалить блок с `dependencies` и `build` в корневом `pom`

2023-06-04 13:06 UTC, AnastasiyaFomkina approved these changes
Перед мерджем лучше удалить блок `<dependencies>` и `<build>` из корневого `pom`, но в целом - это не критично пока что

2023-06-12 19:26 UTC, merged